---
# Unified requirements file supporting both roles and collections

# Ansible Collections
collections:
  - name: community.general
    version: ">=5.0.0"
  - name: ansible.posix
    version: ">=1.4.0"

# Ansible Roles
roles:
  - name: geerlingguy.docker
    version: "6.1.0"
  - src: https://github.com/geerlingguy/ansible-role-nodejs
    name: geerlingguy.nodejs
    version: "6.0.0"
