version: 2
project_name: packer-plugin-ansible-navigator

before:
  hooks:
    - go mod download

builds:
  - id: plugin-check
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      pre:
        - cmd: "go build -o packer-plugin-ansible-navigator {{ .Env.ALL_LDFLAGS}} ."
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256

release:
  github:
    owner: SolomonHD
    name: packer-plugin-ansible-navigator
  draft: false
  name_template: "v{{ .Version }}"
  extra_files:
    - glob: ./{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS

publishers:
  - name: post-release
    cmd: ./scripts/post-release.sh
    env:
      - RELEASE_VERSION={{ .Version }}
      - PROJECT_NAME={{ .ProjectName }}

sboms:
  - artifacts: none

signs:
  - artifacts: none

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
