version: 2
project_name: packer-plugin-ansible-navigator

env:
  - API_VERSION=x5.0

before:
  hooks:
    - go mod download

builds:
  - id: plugin-check
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      pre:
        - cmd: "go build -o packer-plugin-ansible-navigator ."
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"

archives:
  - id: plugin-archive
    format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      mode: 0755
    rlcp: true

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256

release:
  github:
    owner: SolomonHD
    name: packer-plugin-ansible-navigator
  draft: false
  name_template: "v{{ .Version }}"
  extra_files:
    - glob: ./dist/{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
