version: 2

project_name: packer-plugin-ansible-navigator

builds:
  - id: packer-plugin-ansible-navigator
    main: .
    binary: packer-plugin-ansible-navigator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_v{{ .Version }}_x5_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: false
    files:
      - none*

checksum:
  # Packer >=1.10 expects x5 in the checksum filename
  name_template: "{{ .ProjectName }}_v{{ .Version }}_x5_SHA256SUMS"

release:
  github:
    owner: SolomonHD
    name: packer-plugin-ansible-navigator
  draft: false
  prerelease: false

changelog:
  use: git
