version: 2

project_name: packer-plugin-ansible-navigator

builds:
  - id: plugin
    main: .
    binary: packer-plugin-ansible-navigator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    format: binary
    name_template: "{{ .ProjectName }}_v{{ .Version }}_x5.0_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256

release:
  github:
    owner: SolomonHD
    name: packer-plugin-ansible-navigator
  draft: false
  prerelease: false

changelog:
  use: git
