// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package ansiblenavigator

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName         *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType       *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion       *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug             *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce             *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError           *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars          map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars     []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	Command                 *string           `mapstructure:"command" cty:"command" hcl:"command"`
	NavigatorMode           *string           `mapstructure:"navigator_mode" cty:"navigator_mode" hcl:"navigator_mode"`
	ExecutionEnvironment    *string           `mapstructure:"execution_environment" cty:"execution_environment" hcl:"execution_environment"`
	WorkDir                 *string           `mapstructure:"work_dir" cty:"work_dir" hcl:"work_dir"`
	KeepGoing               *bool             `mapstructure:"keep_going" cty:"keep_going" hcl:"keep_going"`
	StructuredLogging       *bool             `mapstructure:"structured_logging" cty:"structured_logging" hcl:"structured_logging"`
	LogOutputPath           *string           `mapstructure:"log_output_path" cty:"log_output_path" hcl:"log_output_path"`
	VerboseTaskOutput       *bool             `mapstructure:"verbose_task_output" cty:"verbose_task_output" hcl:"verbose_task_output"`
	ExtraArguments          []string          `mapstructure:"extra_arguments" cty:"extra_arguments" hcl:"extra_arguments"`
	AnsibleEnvVars          []string          `mapstructure:"ansible_env_vars" cty:"ansible_env_vars" hcl:"ansible_env_vars"`
	PlaybookFile            *string           `mapstructure:"playbook_file" cty:"playbook_file" hcl:"playbook_file"`
	Plays                   []FlatPlay        `mapstructure:"play" cty:"play" hcl:"play"`
	RequirementsFile        *string           `mapstructure:"requirements_file" cty:"requirements_file" hcl:"requirements_file"`
	RolesCacheDir           *string           `mapstructure:"roles_cache_dir" cty:"roles_cache_dir" hcl:"roles_cache_dir"`
	OfflineMode             *bool             `mapstructure:"offline_mode" cty:"offline_mode" hcl:"offline_mode"`
	ForceUpdate             *bool             `mapstructure:"force_update" cty:"force_update" hcl:"force_update"`
	AnsibleSSHExtraArgs     []string          `mapstructure:"ansible_ssh_extra_args" cty:"ansible_ssh_extra_args" hcl:"ansible_ssh_extra_args"`
	Groups                  []string          `mapstructure:"groups" cty:"groups" hcl:"groups"`
	EmptyGroups             []string          `mapstructure:"empty_groups" cty:"empty_groups" hcl:"empty_groups"`
	HostAlias               *string           `mapstructure:"host_alias" cty:"host_alias" hcl:"host_alias"`
	User                    *string           `mapstructure:"user" cty:"user" hcl:"user"`
	LocalPort               *int              `mapstructure:"local_port" cty:"local_port" hcl:"local_port"`
	SSHHostKeyFile          *string           `mapstructure:"ssh_host_key_file" cty:"ssh_host_key_file" hcl:"ssh_host_key_file"`
	SSHAuthorizedKeyFile    *string           `mapstructure:"ssh_authorized_key_file" cty:"ssh_authorized_key_file" hcl:"ssh_authorized_key_file"`
	AdapterKeyType          *string           `mapstructure:"ansible_proxy_key_type" cty:"ansible_proxy_key_type" hcl:"ansible_proxy_key_type"`
	SFTPCmd                 *string           `mapstructure:"sftp_command" cty:"sftp_command" hcl:"sftp_command"`
	SkipVersionCheck        *bool             `mapstructure:"skip_version_check" cty:"skip_version_check" hcl:"skip_version_check"`
	UseSFTP                 *bool             `mapstructure:"use_sftp" cty:"use_sftp" hcl:"use_sftp"`
	InventoryDirectory      *string           `mapstructure:"inventory_directory" cty:"inventory_directory" hcl:"inventory_directory"`
	InventoryFileTemplate   *string           `mapstructure:"inventory_file_template" cty:"inventory_file_template" hcl:"inventory_file_template"`
	InventoryFile           *string           `mapstructure:"inventory_file" cty:"inventory_file" hcl:"inventory_file"`
	Limit                   *string           `mapstructure:"limit" cty:"limit" hcl:"limit"`
	KeepInventoryFile       *bool             `mapstructure:"keep_inventory_file" cty:"keep_inventory_file" hcl:"keep_inventory_file"`
	GalaxyFile              *string           `mapstructure:"galaxy_file" cty:"galaxy_file" hcl:"galaxy_file"`
	GalaxyCommand           *string           `mapstructure:"galaxy_command" cty:"galaxy_command" hcl:"galaxy_command"`
	GalaxyForceInstall      *bool             `mapstructure:"galaxy_force_install" cty:"galaxy_force_install" hcl:"galaxy_force_install"`
	GalaxyForceWithDeps     *bool             `mapstructure:"galaxy_force_with_deps" cty:"galaxy_force_with_deps" hcl:"galaxy_force_with_deps"`
	RolesPath               *string           `mapstructure:"roles_path" cty:"roles_path" hcl:"roles_path"`
	CollectionsPath         *string           `mapstructure:"collections_path" cty:"collections_path" hcl:"collections_path"`
	Collections             []string          `mapstructure:"collections" cty:"collections" hcl:"collections"`
	CollectionsCacheDir     *string           `mapstructure:"collections_cache_dir" cty:"collections_cache_dir" hcl:"collections_cache_dir"`
	CollectionsOffline      *bool             `mapstructure:"collections_offline" cty:"collections_offline" hcl:"collections_offline"`
	CollectionsForceUpdate  *bool             `mapstructure:"collections_force_update" cty:"collections_force_update" hcl:"collections_force_update"`
	CollectionsRequirements *string           `mapstructure:"collections_requirements" cty:"collections_requirements" hcl:"collections_requirements"`
	UseProxy                *bool             `mapstructure:"use_proxy" cty:"use_proxy" hcl:"use_proxy"`
	WinRMUseHTTP            *bool             `mapstructure:"ansible_winrm_use_http" cty:"ansible_winrm_use_http" hcl:"ansible_winrm_use_http"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"command":                    &hcldec.AttrSpec{Name: "command", Type: cty.String, Required: false},
		"navigator_mode":             &hcldec.AttrSpec{Name: "navigator_mode", Type: cty.String, Required: false},
		"execution_environment":      &hcldec.AttrSpec{Name: "execution_environment", Type: cty.String, Required: false},
		"work_dir":                   &hcldec.AttrSpec{Name: "work_dir", Type: cty.String, Required: false},
		"keep_going":                 &hcldec.AttrSpec{Name: "keep_going", Type: cty.Bool, Required: false},
		"structured_logging":         &hcldec.AttrSpec{Name: "structured_logging", Type: cty.Bool, Required: false},
		"log_output_path":            &hcldec.AttrSpec{Name: "log_output_path", Type: cty.String, Required: false},
		"verbose_task_output":        &hcldec.AttrSpec{Name: "verbose_task_output", Type: cty.Bool, Required: false},
		"extra_arguments":            &hcldec.AttrSpec{Name: "extra_arguments", Type: cty.List(cty.String), Required: false},
		"ansible_env_vars":           &hcldec.AttrSpec{Name: "ansible_env_vars", Type: cty.List(cty.String), Required: false},
		"playbook_file":              &hcldec.AttrSpec{Name: "playbook_file", Type: cty.String, Required: false},
		"play":                       &hcldec.BlockListSpec{TypeName: "play", Nested: hcldec.ObjectSpec((*FlatPlay)(nil).HCL2Spec())},
		"requirements_file":          &hcldec.AttrSpec{Name: "requirements_file", Type: cty.String, Required: false},
		"roles_cache_dir":            &hcldec.AttrSpec{Name: "roles_cache_dir", Type: cty.String, Required: false},
		"offline_mode":               &hcldec.AttrSpec{Name: "offline_mode", Type: cty.Bool, Required: false},
		"force_update":               &hcldec.AttrSpec{Name: "force_update", Type: cty.Bool, Required: false},
		"ansible_ssh_extra_args":     &hcldec.AttrSpec{Name: "ansible_ssh_extra_args", Type: cty.List(cty.String), Required: false},
		"groups":                     &hcldec.AttrSpec{Name: "groups", Type: cty.List(cty.String), Required: false},
		"empty_groups":               &hcldec.AttrSpec{Name: "empty_groups", Type: cty.List(cty.String), Required: false},
		"host_alias":                 &hcldec.AttrSpec{Name: "host_alias", Type: cty.String, Required: false},
		"user":                       &hcldec.AttrSpec{Name: "user", Type: cty.String, Required: false},
		"local_port":                 &hcldec.AttrSpec{Name: "local_port", Type: cty.Number, Required: false},
		"ssh_host_key_file":          &hcldec.AttrSpec{Name: "ssh_host_key_file", Type: cty.String, Required: false},
		"ssh_authorized_key_file":    &hcldec.AttrSpec{Name: "ssh_authorized_key_file", Type: cty.String, Required: false},
		"ansible_proxy_key_type":     &hcldec.AttrSpec{Name: "ansible_proxy_key_type", Type: cty.String, Required: false},
		"sftp_command":               &hcldec.AttrSpec{Name: "sftp_command", Type: cty.String, Required: false},
		"skip_version_check":         &hcldec.AttrSpec{Name: "skip_version_check", Type: cty.Bool, Required: false},
		"use_sftp":                   &hcldec.AttrSpec{Name: "use_sftp", Type: cty.Bool, Required: false},
		"inventory_directory":        &hcldec.AttrSpec{Name: "inventory_directory", Type: cty.String, Required: false},
		"inventory_file_template":    &hcldec.AttrSpec{Name: "inventory_file_template", Type: cty.String, Required: false},
		"inventory_file":             &hcldec.AttrSpec{Name: "inventory_file", Type: cty.String, Required: false},
		"limit":                      &hcldec.AttrSpec{Name: "limit", Type: cty.String, Required: false},
		"keep_inventory_file":        &hcldec.AttrSpec{Name: "keep_inventory_file", Type: cty.Bool, Required: false},
		"galaxy_file":                &hcldec.AttrSpec{Name: "galaxy_file", Type: cty.String, Required: false},
		"galaxy_command":             &hcldec.AttrSpec{Name: "galaxy_command", Type: cty.String, Required: false},
		"galaxy_force_install":       &hcldec.AttrSpec{Name: "galaxy_force_install", Type: cty.Bool, Required: false},
		"galaxy_force_with_deps":     &hcldec.AttrSpec{Name: "galaxy_force_with_deps", Type: cty.Bool, Required: false},
		"roles_path":                 &hcldec.AttrSpec{Name: "roles_path", Type: cty.String, Required: false},
		"collections_path":           &hcldec.AttrSpec{Name: "collections_path", Type: cty.String, Required: false},
		"collections":                &hcldec.AttrSpec{Name: "collections", Type: cty.List(cty.String), Required: false},
		"collections_cache_dir":      &hcldec.AttrSpec{Name: "collections_cache_dir", Type: cty.String, Required: false},
		"collections_offline":        &hcldec.AttrSpec{Name: "collections_offline", Type: cty.Bool, Required: false},
		"collections_force_update":   &hcldec.AttrSpec{Name: "collections_force_update", Type: cty.Bool, Required: false},
		"collections_requirements":   &hcldec.AttrSpec{Name: "collections_requirements", Type: cty.String, Required: false},
		"use_proxy":                  &hcldec.AttrSpec{Name: "use_proxy", Type: cty.Bool, Required: false},
		"ansible_winrm_use_http":     &hcldec.AttrSpec{Name: "ansible_winrm_use_http", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatPlay is an auto-generated flat version of Play.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatPlay struct {
	Name       *string           `mapstructure:"name" cty:"name" hcl:"name"`
	Target     *string           `mapstructure:"target" cty:"target" hcl:"target"`
	ExtraVars  map[string]string `mapstructure:"extra_vars" cty:"extra_vars" hcl:"extra_vars"`
	Tags       []string          `mapstructure:"tags" cty:"tags" hcl:"tags"`
	VarsFiles  []string          `mapstructure:"vars_files" cty:"vars_files" hcl:"vars_files"`
	Become     *bool             `mapstructure:"become" cty:"become" hcl:"become"`
	BecomeUser *string           `mapstructure:"become_user" cty:"become_user" hcl:"become_user"`
	SkipTags   []string          `mapstructure:"skip_tags" cty:"skip_tags" hcl:"skip_tags"`
}

// FlatMapstructure returns a new FlatPlay.
// FlatPlay is an auto-generated flat version of Play.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Play) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatPlay)
}

// HCL2Spec returns the hcl spec of a Play.
// This spec is used by HCL to read the fields of Play.
// The decoded values from this spec will then be applied to a FlatPlay.
func (*FlatPlay) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":        &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"target":      &hcldec.AttrSpec{Name: "target", Type: cty.String, Required: false},
		"extra_vars":  &hcldec.AttrSpec{Name: "extra_vars", Type: cty.Map(cty.String), Required: false},
		"tags":        &hcldec.AttrSpec{Name: "tags", Type: cty.List(cty.String), Required: false},
		"vars_files":  &hcldec.AttrSpec{Name: "vars_files", Type: cty.List(cty.String), Required: false},
		"become":      &hcldec.AttrSpec{Name: "become", Type: cty.Bool, Required: false},
		"become_user": &hcldec.AttrSpec{Name: "become_user", Type: cty.String, Required: false},
		"skip_tags":   &hcldec.AttrSpec{Name: "skip_tags", Type: cty.List(cty.String), Required: false},
	}
	return s
}
