// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package ansiblenavigatorlocal

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName      *string                `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType    *string                `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion    *string                `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug          *bool                  `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce          *bool                  `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError        *string                `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars       map[string]string      `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars  []string               `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	Command              *string                `mapstructure:"command" cty:"command" hcl:"command"`
	AnsibleNavigatorPath []string               `mapstructure:"ansible_navigator_path" cty:"ansible_navigator_path" hcl:"ansible_navigator_path"`
	VersionCheckTimeout  *string                `mapstructure:"version_check_timeout" cty:"version_check_timeout" hcl:"version_check_timeout"`
	GalaxyForceInstall   *bool                  `mapstructure:"galaxy_force_install" cty:"galaxy_force_install" hcl:"galaxy_force_install"`
	WorkDir              *string                `mapstructure:"work_dir" cty:"work_dir" hcl:"work_dir"`
	KeepGoing            *bool                  `mapstructure:"keep_going" cty:"keep_going" hcl:"keep_going"`
	StructuredLogging    *bool                  `mapstructure:"structured_logging" cty:"structured_logging" hcl:"structured_logging"`
	LogOutputPath        *string                `mapstructure:"log_output_path" cty:"log_output_path" hcl:"log_output_path"`
	VerboseTaskOutput    *bool                  `mapstructure:"verbose_task_output" cty:"verbose_task_output" hcl:"verbose_task_output"`
	Plays                []FlatPlay             `mapstructure:"play" cty:"play" hcl:"play"`
	RequirementsFile     *string                `mapstructure:"requirements_file" cty:"requirements_file" hcl:"requirements_file"`
	CollectionsCacheDir  *string                `mapstructure:"collections_cache_dir" cty:"collections_cache_dir" hcl:"collections_cache_dir"`
	RolesCacheDir        *string                `mapstructure:"roles_cache_dir" cty:"roles_cache_dir" hcl:"roles_cache_dir"`
	OfflineMode          *bool                  `mapstructure:"offline_mode" cty:"offline_mode" hcl:"offline_mode"`
	ForceUpdate          *bool                  `mapstructure:"force_update" cty:"force_update" hcl:"force_update"`
	NavigatorConfig      map[string]interface{} `mapstructure:"navigator_config" cty:"navigator_config" hcl:"navigator_config"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"command":                    &hcldec.AttrSpec{Name: "command", Type: cty.String, Required: false},
		"ansible_navigator_path":     &hcldec.AttrSpec{Name: "ansible_navigator_path", Type: cty.List(cty.String), Required: false},
		"version_check_timeout":      &hcldec.AttrSpec{Name: "version_check_timeout", Type: cty.String, Required: false},
		"galaxy_force_install":       &hcldec.AttrSpec{Name: "galaxy_force_install", Type: cty.Bool, Required: false},
		"work_dir":                   &hcldec.AttrSpec{Name: "work_dir", Type: cty.String, Required: false},
		"keep_going":                 &hcldec.AttrSpec{Name: "keep_going", Type: cty.Bool, Required: false},
		"structured_logging":         &hcldec.AttrSpec{Name: "structured_logging", Type: cty.Bool, Required: false},
		"log_output_path":            &hcldec.AttrSpec{Name: "log_output_path", Type: cty.String, Required: false},
		"verbose_task_output":        &hcldec.AttrSpec{Name: "verbose_task_output", Type: cty.Bool, Required: false},
		"play":                       &hcldec.BlockListSpec{TypeName: "play", Nested: hcldec.ObjectSpec((*FlatPlay)(nil).HCL2Spec())},
		"requirements_file":          &hcldec.AttrSpec{Name: "requirements_file", Type: cty.String, Required: false},
		"collections_cache_dir":      &hcldec.AttrSpec{Name: "collections_cache_dir", Type: cty.String, Required: false},
		"roles_cache_dir":            &hcldec.AttrSpec{Name: "roles_cache_dir", Type: cty.String, Required: false},
		"offline_mode":               &hcldec.AttrSpec{Name: "offline_mode", Type: cty.Bool, Required: false},
		"force_update":               &hcldec.AttrSpec{Name: "force_update", Type: cty.Bool, Required: false},
		// NOTE: Type manually changed from cty.Map(cty.String) to cty.DynamicPseudoType
		// to support nested map structures in navigator_config (see fix-navigator-config-hcl2-type)
		"navigator_config": &hcldec.AttrSpec{Name: "navigator_config", Type: cty.DynamicPseudoType, Required: false},
	}
	return s
}

// FlatPlay is an auto-generated flat version of Play.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatPlay struct {
	Name      *string           `mapstructure:"name" cty:"name" hcl:"name"`
	Target    *string           `mapstructure:"target" cty:"target" hcl:"target"`
	ExtraVars map[string]string `mapstructure:"extra_vars" cty:"extra_vars" hcl:"extra_vars"`
	Tags      []string          `mapstructure:"tags" cty:"tags" hcl:"tags"`
	VarsFiles []string          `mapstructure:"vars_files" cty:"vars_files" hcl:"vars_files"`
	Become    *bool             `mapstructure:"become" cty:"become" hcl:"become"`
}

// FlatMapstructure returns a new FlatPlay.
// FlatPlay is an auto-generated flat version of Play.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Play) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatPlay)
}

// HCL2Spec returns the hcl spec of a Play.
// This spec is used by HCL to read the fields of Play.
// The decoded values from this spec will then be applied to a FlatPlay.
func (*FlatPlay) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":       &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"target":     &hcldec.AttrSpec{Name: "target", Type: cty.String, Required: false},
		"extra_vars": &hcldec.AttrSpec{Name: "extra_vars", Type: cty.Map(cty.String), Required: false},
		"tags":       &hcldec.AttrSpec{Name: "tags", Type: cty.List(cty.String), Required: false},
		"vars_files": &hcldec.AttrSpec{Name: "vars_files", Type: cty.List(cty.String), Required: false},
		"become":     &hcldec.AttrSpec{Name: "become", Type: cty.Bool, Required: false},
	}
	return s
}
